spring:
  application:
    name: config-server
  cloud:
      config:
        server:
          git:
            uri:  https://github.com/Sucreyy1/configuration #配置git仓库的地址
#            search-paths: config-repo #配置在哪个目录下搜索配置文件
server:
  port: 9999
